const fs=require('fs'),vm=require('vm'),assert=require('assert');const base=require('path').join(__dirname,'..');const checker=fs.readFileSync(base+'/checker-content.js','utf8'),worker=fs.readFileSync(base+'/worker.js','utf8');const c={PF_GRADE_AREA:{imi_s:.72,imi_l:1.2},URL};vm.createContext(c);vm.runInContext(checker.slice(checker.indexOf('function parsePriceText('),checker.indexOf('function scrapeByText(')),c);vm.runInContext(worker.slice(worker.indexOf('function listMapping('),worker.indexOf('async function readList(')),c);
assert.equal(c.parsePriceText('18,000원'),18000);assert.equal(c.parsePriceText('할인가 18,000원'),18000);assert.equal(c.parsePriceText('10% 20,000원 18,000원'),null);assert.equal(c.parsePriceText('배송비 3,000원'),null);
const node=(text,excluded=false)=>({textContent:text,closest:()=>excluded?{}:null,querySelectorAll:()=>[],getAttribute:()=>null});assert.equal(c.extractPrice({querySelectorAll:()=>[node('20,000원',true),node('18,000원'),node('10%')]}),18000);assert.equal(c.extractPrice({querySelectorAll:()=>[node('20,000원'),node('18,000원')]}),null);
const pu={mapping:{product_type:'pu',grade_id:'iiia',thickness:50,is_bundle:'false'}};assert.equal(c.listMapping(pu).area,2);assert.equal(c.listMapping({mapping:{product_type:'pf',grade_id:'imi_l',thickness:50}}).area,1.2);assert.equal(c.listMapping({mapping:{product_type:'pf',grade_id:'imi',thickness:50}}),null);assert.equal(c.listMapping({mapping:{...pu.mapping,is_bundle:true}}),null);assert.equal(c.listMapping({mapping:{product_type:'iso',grade_id:'1ho',thickness:50,area:1}}),null);
const ui=fs.readFileSync(require('path').join(base,'../../js/pricing-check-test.js'),'utf8');vm.runInContext(ui.slice(ui.indexOf('  function compareExtensionVersions('),ui.indexOf('  let busy=false;')),c);assert(c.compareExtensionVersions('0.29.10','0.29.6')>0);assert(c.compareExtensionVersions('0.29.5','0.29.6')<0);
c.getTablePrice=()=>18000;c.readList=async()=>({products:[{productId:'1',name:'경질우레탄 종류 선택 단품',price:18000},{productId:'2',name:'수입PF 50T',price:19000}]});vm.runInContext(worker.slice(worker.indexOf('function pageParamOf('),worker.indexOf('async function processNext(')),c);const state={listQueue:['https://smartstore.naver.com/energuardcompany/category/ALL?cp=1'],listVisited:[],items:[{...pu,productId:'1'},{productId:'2',mapping:{product_type:'pf',grade_id:'imi_s',thickness:50}}],done:0,rows:[],pricing:{}};c.listStep(state).then(()=>{assert.equal(state.done,2);assert.equal(state.rows[0].status,'대표가 일치');assert.equal(state.rows[1].status,'대표가 불일치');console.log('PASS robust price parsing, PU/PF fixed-size eligibility, bundles excluded, title false-positive removed, list comparison, semantic version');}).catch(e=>{console.error(e);process.exit(1)});

vm.runInContext(checker.slice(checker.indexOf('function extractListPrice('),checker.indexOf('function extractName(')),c);
const link=(id,fields)=>({getAttribute:k=>k==='data-shp-contents-id'?id:JSON.stringify(fields)});
assert.equal(c.extractListPrice(link('11638984898',[{key:'price',value:'54400'},{key:'prod_no',value:'11584893858'}]),'11638984898'),54400);
assert.equal(c.extractListPrice(link('11584893858',[{key:'price',value:'54400'}]),'11638984898'),null);
assert.equal(c.extractListPrice(link('1',[{key:'price',value:'10% 54400'}]),'1'),null);